### ISSUE TITLE
Project root detection looks questionable to me

### ISSUE THREAD

**Issue by rgrinberg** [emacs-lsp/lsp-ocaml#2]
* .merlin files are supposed to be created per every source directory. Hence a single project will have many of them

* opam files are better, but the convention is now to have a `<project>.opam` file checked in. Also, this doesn't always work because you can also have an `opam` subdir in your root where opam files may exist.

**Comment by anmonteiro** [comment]
Thanks, that was done in a rush and I agree it's kinda messy. Do you have a better suggestion?

**Comment by rgrinberg** [comment]
I would say either the candidates should be jbuild-workspace, *.opam, and package.json files. Though I'm not sure for package.json, perhaps it's best to ask bucklescript users.

**Comment by anmonteiro** [comment]
I think for BuckleScript we may want to add `bsconfig.json` in there too

**Comment by anmonteiro** [comment]
@rgrinberg does #3 look OK to you?
